import type { Property } from "@/types/property";

export const properties: Property[] = [
  {
    id: "1",
    title: "Modern Luxury Villa",
    address: "123 Oak Street, Beverly Hills, CA 90210",
    price: 2500000,
    bedrooms: 4,
    bathrooms: 3,
    sqft: 3500,
    type: "house",
    status: "for-sale",
    image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop",
    description: "Stunning modern villa with panoramic city views, premium finishes, and resort-style amenities.",
    features: ["Swimming Pool", "Home Office", "Garage", "Garden"],
    yearBuilt: 2020,
    parking: 2,
  },
  {
    id: "2",
    title: "Downtown Penthouse",
    address: "456 Park Avenue, New York, NY 10022",
    price: 4500,
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1800,
    type: "apartment",
    status: "for-rent",
    image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop",
    description: "Luxury penthouse in the heart of downtown with floor-to-ceiling windows and modern amenities.",
    features: ["City View", "Concierge", "Fitness Center", "Rooftop Access"],
    yearBuilt: 2018,
    parking: 1,
  },
  {
    id: "3",
    title: "Family Home with Garden",
    address: "789 Maple Drive, Seattle, WA 98101",
    price: 750000,
    bedrooms: 3,
    bathrooms: 2,
    sqft: 2400,
    type: "house",
    status: "for-sale",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop",
    description: "Beautiful family home with spacious backyard, updated kitchen, and cozy living spaces.",
    features: ["Large Garden", "Fireplace", "Hardwood Floors", "Renovated Kitchen"],
    yearBuilt: 1995,
    parking: 2,
  },
  {
    id: "4",
    title: "Waterfront Condo",
    address: "321 Harbor View, Miami, FL 33139",
    price: 3200,
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1500,
    type: "condo",
    status: "for-rent",
    image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop",
    description: "Stunning waterfront condo with ocean views, balcony, and access to private beach.",
    features: ["Ocean View", "Balcony", "Beach Access", "Pool"],
    yearBuilt: 2015,
    parking: 1,
  },
  {
    id: "5",
    title: "Cozy Townhouse",
    address: "555 Elm Street, Boston, MA 02108",
    price: 580000,
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1600,
    type: "townhouse",
    status: "for-sale",
    image: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800&h=600&fit=crop",
    description: "Charming townhouse in historic district with modern updates and private parking.",
    features: ["Historic District", "Updated Kitchen", "Private Parking", "Low Maintenance"],
    yearBuilt: 1985,
    parking: 1,
  },
  {
    id: "6",
    title: "Executive Apartment",
    address: "888 Business District, San Francisco, CA 94102",
    price: 5200,
    bedrooms: 1,
    bathrooms: 1,
    sqft: 1200,
    type: "apartment",
    status: "for-rent",
    image: "https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=800&h=600&fit=crop",
    description: "Sleek executive apartment in prime location, perfect for professionals.",
    features: ["Walk to Work", "Modern Design", "High-Speed Internet", "Gym Access"],
    yearBuilt: 2022,
    parking: 0,
  },
];

export function getPropertyById(id: string): Property | undefined {
  return properties.find((property) => property.id === id);
}

export function getFeaturedProperties(): Property[] {
  return properties.slice(0, 3);
}

